apiVersion: apps/v1
kind: Deployment
metadata:
  name: qsr-api
  namespace: rotf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qsr-api
  template:
    metadata:
      labels:
        app: qsr-api
    spec:
      containers:
      - name: qsr-api
        image: gcr.io/anthos-edge-361104/qsr-api
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: rotf-db
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: rotf-db
                key: DB_USER
          - name: DB_PWD
            valueFrom:
              configMapKeyRef:
                name: rotf-db
                key: DB_PWD
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: rotf-db
                key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: qsr-api
  namespace: rotf
spec:
  type: ClusterIP
  selector:
    app: qsr-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000