apiVersion: apps/v1
kind: Deployment
metadata:
  name: qsr-ui
  namespace: rotf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qsr-ui
  template:
    metadata:
      labels:
        app: qsr-ui
    spec:
      containers:
      - name: qsr-ui
        image: gcr.io/anthos-edge-361104/qsr-ui
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        env:
          - name: REACT_APP_BACKEND
            value: "qsr-api:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: qsr-ui-service
  namespace: rotf
spec:
  type: LoadBalancer
  selector:
    app: qsr-ui
  ports:
  - name: http
    port: 80
    targetPort: 3000