apiVersion: v1
kind: Namespace
metadata:
  name: pos
  annotations:
    istio-injection: enabled istio.io/rev-
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  namespace: pos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
      - name: pos
        image: gcr.io/anthos-edge-361104/pos:v1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pos
  namespace: pos
spec:
  type: LoadBalancer
  selector:
    app: pos
  ports:
  - name: http
    port: 80
    targetPort: 80